version: '3'
services:
    nginx:
        image: nginx:1.12
        container_name: ps2alerts-nginx
        ports:
            - "80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=dev.ps2alerts.com
    composer:
        image: composer/composer
        volumes:
            - .:/app
        command: install
    npm:
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
            - .:/data
        command: npm install
    bower:
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
            - ./public:/data
        command: bower install
    grunt:
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
            - .:/data
        command: "grunt envDev"
    gruntwatch:
        image: digitallyseamless/nodejs-bower-grunt
        volumes:
            - .:/data
        command: "grunt watch"
networks:
    default:
        external:
            name: local
