---
- hosts: localhost
  tasks:
    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present

    - name: Build Website Base image (grab a snickers)
      docker_image:
        name: ps2alerts/website # local image
        state: present
        source: build
        tag: base
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}/../base"

    - name: Build Website Dev Container
      docker_image:
        name: ps2alerts/website
        state: present
        source: build
        tag: dev
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}"

    - name: Get user's current UID
      command: "id -u {{ ansible_user_id }}"
      register: id

    - name: Run composer
      docker_container:
        name: ps2alerts-api-composer
        image: composer/composer
        volumes:
          - "{{ playbook_dir }}/../../app:/app"
        user: "{{ id.stdout }}:{{ id.stdout }}"
        command: install

    - name: Start Website Dev Container
      docker_container:
        name: ps2alerts-website
        image: ps2alerts/website:dev
        state: started
        restart: yes
        volumes:
          - "{{ playbook_dir }}/../../app:/var/www/html:rw"
        ports:
          - 80:80
          - 443:443
        networks:
          - name: "ps2alerts"
        env:
          API_URL: "http://dev.api.ps2alerts.com"
          BASE_URL: "http://dev.ps2alerts.com"
          ENVIRONMENT: "development"
          VERSION: "12345"