---
- hosts: localhost

  vars_files:
    - "{{ playbook_dir }}/../../vars.yml"

  tasks:
    - name: Stop Website Container
      docker_container:
        name: ps2alerts-website
        state: stopped
