---
# We're having to do this as Terraform currently doesn't support custom CRDs :'(
# https://github.com/hashicorp/terraform-provider-kubernetes/issues/215
- name: Create K8s LetsEncrypt certificate issuer
  k8s:
    state: present
    namespace: default
    definition:
      apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: "{{ identifier }}"
      spec:
        acme:
          email: matt@mattcavanagh.me
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: "{{ identifier }}"
          solvers:
            - http01:
                ingress:
                  class: nginx
