---
name: Ansible Linter
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            provisioning/dev/start.yml
            provisioning/dev/stop.yml
            provisioning/init.yml
          args: ""
